### ISSUE TITLE
ImportError when used with other backports

### ISSUE THREAD

**Issue by jaraco** [jaraco/configparser#17]
**[Original report](https://bitbucket.org/ambv/configparser/issue/17) by Frederik Rietdijk (Bitbucket: [FRidh](https://bitbucket.org/FRidh), GitHub: [FRidh](https://github.com/FRidh)).**

----------------------------------------

If we have several backport packages (`configparser`, `backports.shutil_get_terminal_size`, `backports.ssl_match_hostname`), then we get an `ImportError` when we try to use these packages. At least

```
python -c 'import backports.shutil_get_terminal_size'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'backports.shutil_get_terminal_size'
```

We fixed the issue with 
https://github.com/FRidh/nixpkgs/blob/d7378da0280ebc0b59d0d198fd86b2d4a9eace41/pkgs/development/python-modules/configparser/0001-namespace-fix.patch

Discussion on the issue.
https://github.com/NixOS/nixpkgs/issues/23855

**Comment by Chazzz** [comment]
@jaraco Awesome, thanks for the help!
