### ISSUE TITLE
README.rst -- Use unicode string litterals in code sample

### ISSUE THREAD

**Issue by jaraco** [jaraco/configparser#18]
**[Original report](https://bitbucket.org/ambv/configparser/issue/18) by Laurent LAPORTE (Bitbucket: [Tantale](https://bitbucket.org/Tantale), GitHub: [Tantale](https://github.com/Tantale)).**

----------------------------------------

Since the purpose of this library is to provide a backport to old Python versions, notably Python 2.7, it could be a good thing to use explicitly unicode string literals in the code sample:

    >>> parser = ConfigParser()
    >>> parser.read_string(u"""
    [DEFAULT]
    location = upper left
    visible = yes
    editable = no
    color = blue

    [main]
    title = Main Menu
    color = green

    [options]
    title = Options
    """)
    >>> parser['main']['color']
    u'green'
    >>> parser['main']['editable']
    u'no'
    >>> section = parser['options']
    >>> section['title']
    u'Options'
    >>> section['title'] = 'Options (editable: %(editable)s)'
    >>> section['title']
    u'Options (editable: no)'

_notice the "u" prefix before quotes._

**Comment by tantale** [comment]
You're welcome.
