### ISSUE TITLE
What's the version scheme?

### ISSUE THREAD

**Issue by jaraco** [jaraco/configparser#25]
With the 3.5.1 release, I made an 0.0.1 release because it seems to me the versions of this project are attempting to track with Python releases... and I wanted to be careful to fix the packaging without conflicting too much with the existing version scheme. Maybe it should have been 3.5.0r2... but I'd rather use simple version numbers.

Going forward, I'm tempted to adopt semver and allow the version numbers to deviate from what's in stdlib. I'm open to thoughts or suggestions.

**Comment by asottile** [comment]
semver sg2m

**Comment by jaraco** [comment]
I do see there is a [documented versioning scheme](https://github.com/jaraco/configparser/blob/master/README.rst#versioning). I think I'll do a sync with upstream changes first and then decide if there's a need to change the version scheme.
