### ISSUE TITLE
3.5.2 breaks config parsing in flake8 on python 2.7

### ISSUE THREAD

**Issue by harkylton** [jaraco/configparser#27]
In the line `if PY2 and isinstance(filenames, bytes) and sys.py3kwarning:`, the addition of `and sys.py3kwarning` makes it so flake8 can't read config files. `sys.py3kwarning` seems to only be `True` if you pass `-3` to the python interpreter, and this is not set by default in `flake8`.

**Comment by gvangool** [comment]
I have created a patch for this, https://github.com/gvangool/configparser/tree/fix-regression-in-3.5.2. But the current master is already updated to match the Python 3.7 branches

**Comment by elwinarens** [comment]
Well hello there

**Comment by jaraco** [comment]
Will have a fix shortly.

**Comment by jaraco** [comment]
Fix released as 3.5.3.
