### ISSUE TITLE
License missing from PyPI packages

### ISSUE THREAD

**Issue by jakirkham** [jaraco/configparser#33]
Appears there is a license file in this repo, but it is missing from the sdist and wheels on PyPI. Would be great if the license file could be included in future releases to aid downstream users and packagers.

**Comment by jaraco** [comment]
This issue has been fixed in #32 (I verified the behavior locally). I'll cut a new release.

**Comment by jaraco** [comment]
Released as 3.8.0.

**Comment by jakirkham** [comment]
Thanks :)
