### ISSUE TITLE
Trouble building on Windows

### ISSUE THREAD

**Issue by jakirkham** [jaraco/configparser#34]
We've been having some issues with the build of this package in conda-forge. Our build is just using `pip install` internally to install the package, but it runs into some kind of encoding error. More details and logs can be found in issue ( https://github.com/conda-forge/configparser-feedstock/issues/21 ).

```
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 160: character maps to <undefined>
```

**Comment by jaraco** [comment]
I can say with confidence that the issue stems from the UTF-8 encoding on the setup.cfg and [this line in particular](https://github.com/jaraco/configparser/blob/2a5bea5ed09ae2d1abae57fe9e4c3882f354cbf5/setup.cfg#L8). In prior releases, the UTF-8 form was only present on Python 3 which may explain why Python 2 versions not failing previously.

Recently, Setuptools released [v40.7.0](https://setuptools.readthedocs.io/en/latest/history.html#v40-7-0) with support for non-ascii in config files. I wonder if that update is sufficient to address the issue.

**Comment by jaraco** [comment]
I've tried building on Windows, and I've replicated the issue, even on v40.8.0, so updating setuptools wasn't sufficient to address the issue.

I suspect the most straightforward way to address the issue within this project would be to convert the author's name to ASCII, something I'm reluctant to do... but I'd like to unblock Windows users first and then devise a long term solution after.

**Comment by jaraco** [comment]
The workaround for this issue is releasing as 3.7.3.

**Comment by jaraco** [comment]
After quickly diving into the traceback, I realized that the encoding needs to be declared in the setup.cfg file.

**Comment by jakirkham** [comment]
Thanks for the fix :)
