### ISSUE TITLE
Invalid Tidelift link

### ISSUE THREAD

**Issue by Harmon758** [jaraco/configparser#36]
https://tidelift.com/subscription/pkg/pypi-configparser, in the changelog and readme, seems to be invalid, showing a Page not found 404 error page.

**Comment by jaraco** [comment]
Thanks for reporting this. I've [reported it in the Tidelift forums](https://forum.tidelift.com/t/link-url-leads-to-404/188). I hope to have more information soon.

**Comment by jaraco** [comment]
Tidelift has fixed the issue on their side and the link now works, unchanged.
