### ISSUE TITLE
Please switch to using Unicode strings across the board

### ISSUE THREAD

**Issue by sahumada** [jaraco/configparser#47]
I recently switched to make DeprecatedWarnings behave like errors using python-2.7.12, pytest-4.3.1, pytest-pylint-0.14.0, pylint-1.9.2, ie, running 'pytest --pylint -W error some_scripts.py' and I my CI started to fail. I had to disable the '-W error' option for now, but I would really like to enable it again. Is this something that can be fixed in configparser?

The warning I get is the following:

```
=============================== warnings summary ===============================
.tox/py27-pylint/lib/python2.7/site-packages/backports/configparser/__init__.py:1311
.tox/py27-pylint/lib/python2.7/site-packages/backports/configparser/__init__.py:1311
.tox/py27-pylint/lib/python2.7/site-packages/backports/configparser/__init__.py:1311
.tox/py27-pylint/lib/python2.7/site-packages/backports/configparser/__init__.py:1311
.tox/py27-pylint/lib/python2.7/site-packages/backports/configparser/__init__.py:1311
.tox/py27-pylint/lib/python2.7/site-packages/backports/configparser/__init__.py:1311
.tox/py27-pylint/lib/python2.7/site-packages/backports/configparser/__init__.py:1311
.tox/py27-pylint/lib/python2.7/site-packages/backports/configparser/__init__.py:1311
.tox/py27-pylint/lib/python2.7/site-packages/backports/configparser/__init__.py:1311
.tox/py27-pylint/lib/python2.7/site-packages/backports/configparser/__init__.py:1311
.tox/py27-pylint/lib/python2.7/site-packages/backports/configparser/__init__.py:1311
.tox/py27-pylint/lib/python2.7/site-packages/backports/configparser/__init__.py:1311
.tox/py27-pylint/lib/python2.7/site-packages/backports/configparser/__init__.py:1311
.tox/py27-pylint/lib/python2.7/site-packages/backports/configparser/__init__.py:1311
.tox/py27-pylint/lib/python2.7/site-packages/backports/configparser/__init__.py:1311
.tox/py27-pylint/lib/python2.7/site-packages/backports/configparser/__init__.py:1311
.tox/py27-pylint/lib/python2.7/site-packages/backports/configparser/__init__.py:1311
.tox/py27-pylint/lib/python2.7/site-packages/backports/configparser/__init__.py:1311: 
DeprecationWarning: You passed a bytestring. Implicitly decoding as UTF-8 string. This will not work on Python 3. Please switch to using Unicode strings across the board.
    section, _, _ = self._validate_value_types(section=section)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

**Comment by jaraco** [comment]
I encountered this issue in #42. I addressed it by suppressing the warnings in its own test suite (because its own test suite is meant to exercise and guarantee that deprecated behavior).

The question is, what are you running that elicits the warning?

**Comment by sahumada** [comment]
I said .. I am forcing warnings to become errors .. the command I am running is 'pytest --pylint -W error some_scripts.py' .. I can maybe try to prepare a small test case and also upload my pylintrc if needed

**Comment by jaraco** [comment]
What I don’t understand is what is calling configparser passing bytes. If you’re running the test suite for configparser, don’t do that. If you’re passing bytes triggering the warning, don’t do that. Help me understand the code path that you think needs updating. Thanks.

**Comment by jaraco** [comment]
Closing as it's gone stale. Feel free to follow up with an example illustrating the (preferably minimal) code path that triggers the warning.

**Comment by ahvigil** [comment]
this warning is a little misleading. In python 2 `byte` and `str` are the same so calling `config_parser.set("section", "option", "value")` and `config_parser.set(b"section", b"option", b"value")` both warn, but in python 3 the first still works perfectly fine and only the second is broken.
