### ISSUE TITLE
Request to add upper bound to requires_python

### ISSUE THREAD

**Issue by thatch** [jaraco/configparser#50]
Currently `setup.cfg` reports

```
python_requires =>=2.6
```

It's a little unclear what your maximum supported version is, but I've run across some packages that specify configparser as a dependency without a marker and it's being included in environments intended for recent versions (like 3.7 and 3.8).

I think the intent from the readme is that it should not be necessary on 3.6+, so I wondered if you would accept a pull request that sets something like

```
python_requires = >=2.6,<3.6"
```

**Comment by jaraco** [comment]
Thanks thatch for the suggestion. Although this project was originally intended just to backport changes for 2.6-3.5, it also has the benefit of backporting changes from 3.7 to 3.6 and 3.8 to 3.7. More importantly, this project aims to export the `backports.configparser` package unconditionally for projects that wish to use the same code across all Pythons. I'd accept a pull request to clarify the readme to that extent.
