### ISSUE TITLE
Cannot properly handle bytestrings

### ISSUE THREAD

**Issue by jimzhou112** [jaraco/configparser#54]
I've found a problem with how configparser handles bytestrings.

Example:
foo.conf
```[config]
byte_string = b')]}\',\n'
```

bar.py
```
path_conf = os.path.abspath(os.path.join(os.path.dirname( __file__ ),'..', 'conf' + "/" + "foo.conf"))
if os.path.exists(path_conf):
    conf_details = configparser.ConfigParser()
    byte_string = conf_details.get('config', 'byte_string')
```

Intended behavior:
```
byte_string2 = b')]}\',\n'
print(byte_string2) # b")]}',\n"
print(len(byte_string2)) # 6
```

```
configparser behavior: 
print(byte_string) # b')]}\',\n'
print(len(byte_string)) # 11
```

**Comment by irgeek** [comment]
The files parsed by configparser are text files based on Windows INI files -- they're not Python files. Python notation inside an INI file is treated as plain text and not interpreted. If you want Python notation inside your configuration file, make it a `.py` file and import it.

If you want to use configparser but need to store binary data in your config, your best bet is base64-encoding it in the config and base64-decoding the value that's fetched from the config.

**Comment by jaraco** [comment]
Thanks for the report and irgeek for the analysis. I agree, the user's expectation is not a supported one.
