### ISSUE TITLE
Lack of setup.py breaks AUR builds

### ISSUE THREAD

**Issue by otisdog8** [jaraco/configparser#66]
Because there isn't a setup.py, the AUR cannot build this package.
See commit: https://github.com/jaraco/configparser/commit/7e01b721c237ee4947e3b9d6e56bb03a028f3f6a
And AUR discussion (comments): https://aur.archlinux.org/packages/python-configparser

Thank you!

**Comment by jaraco** [comment]
The change was by design. See [this explanation](https://github.com/jaraco/jaraco.classes/issues/6#issuecomment-1258777740).

**Comment by jaraco** [comment]
It looks like the correct fix was identified in [this comment](https://aur.archlinux.org/packages/python-configparser#comment-920652).
