### ISSUE TITLE
Compatibility with Python2 and Python3

### ISSUE THREAD

**Issue by Pablitosi4** [jaraco/configparser#71]
Hello, I am working on migrating a project from Python 2 to Python 3, ensuring compatibility so that it works on both Python 2 and Python 3. One of the problems I encountered is that Python 2 requires `import ConfigParser`, while Python 3 requires `import configparser`.

The functionality of the new version of the project futurize, which helps ensure this compatibility, does not solve this problem.

On their project website (https://python-future.org/imports.html), it is stated:

> Note that, as of v0.16.0, python-future **no longer includes an alias for the configparser module because a full backport exists** (see https://pypi.org/project/configparser/).

From this, I concluded that this issue is resolved by the tools of confogparser's project.

After following the link to your project, I see:

> "This package is a backport of the refreshed and enhanced ConfigParser from later Python versions. To use the backport instead of the built-in version, simply import it explicitly as a backport:
> 
> `from backports import configparser`
> 
> **_To use the backport on Python 2 and the built-in version on Python 3,_** use the standard invocation:
> 
> `import configparser`
> 
> For detailed documentation consult the vanilla version at http://docs.python.org/3/library/configparser.html."

However, even after installing with pip install configparser, neither the code `import configparser` nor the code `from backports import configparser ` works when running on Python 2.

Can you explain how to ensure compatibility between Python 2 and Python 3 with configparser?

**Comment by jaraco** [comment]
Thanks for the request. Unfortunately, I'm not able to replicate your finding. In the following command, I'm using docker and jaraco/multipy-tox to get a Python 2 environment that uses pip-run to download "configparser" and then shows that it can import both without error:

```
 @ docker run -it jaraco/multipy-tox py -2.7 -m pip-run -q configparser -- -c "import configparser; import backports.configparser" && echo done
done
```

Here's a session doing things without pip-run to make it more obvious what's happening:

```
 configparser main @ docker run -it jaraco/multipy-tox
  # python2.7 -m pip install configparser
Collecting configparser
  Downloading configparser-4.0.2-py2.py3-none-any.whl (22 kB)
Installing collected packages: configparser
Successfully installed configparser-4.0.2
  # python2.7 -c "import configparser"
  # python2.7 -c "from backports import configparser"
```

Similarly using the canonical "python:2.7" image:

```
 @ docker run -it python:2.7 bash
root@c5e22403ee38:/# pip install configparser
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: configparser in /usr/local/lib/python2.7/site-packages (4.0.2)
WARNING: You are using pip version 20.0.2; however, version 20.3.4 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
root@c5e22403ee38:/# python -c "import configparser"
root@c5e22403ee38:/# python -c "from backports import configparser"
root@c5e22403ee38:/# 
```

As you can see, it seems to be importing just fine.

So there seems to be something wrong with the way you're installing configparser.

Are you sure you're using the right pip? What is the output of your `pip list` and `pip --version`?

**Comment by Pablitosi4** [comment]
Thank you very much for your help, indeed, although my main installation was python2.7, pip installed the package for 3.10. Your answer was very helpful, you helped me!
